include: package:flutter_lints/flutter.yaml

	analyzer:
	  strong-mode:
	    implicit-casts: false
	    implicit-dynamic: false
	  errors:
	    unused_local_variable: warning
	    dead_code: error

	linter:
	  rules:
	    - avoid_print
	    - prefer_const_constructors
	    - annotate_overrides
	    - avoid_init_to_null
	    - sort_constructors_first
	    - prefer_final_locals
	    - prefer_is_empty
	    - avoid_return_types_on_setters
	    - avoid_unused_constructor_parameters